### Fala devs, blz?

Temos a honra de apresentar nossa 5ᵃ lista de exercícios do Curso de Python 2024 ! 🥳

Dessa vez o tema será o módulo 5, que retrata sobre importações de bibliotecas e sobre a biblioteca _Numpy_ - muito importante para realização de códigos matemáticos e melhora de desempenho das operações.

Esperamos que seja um estudo produtivo e que se divirtam aprendendo!

---
### INSTRUÇÕES:

A realização da lista deve ser feita através no Jupyter Notebook.

É primordial enviar as listas para praticar todo o conhecimento adquirido durante o curso.

Este DESAFIO foi elaborado para quebrar a cabeça. Por isso, não desista de tentar e de continuar com o curso. Ao longo das listas, você perceberá que terá cada vez mais ferramentas para completá-las.

Se surgirem dúvidas sobre a lista, assista as monitorias para entender melhor. Se o problema não for resolvido, envie uma mensagem para o formulário de dúvidas.

---

In [49]:
# Vamos começar importando algumas bibliotecas importantes para os exercícios. ps: Escolham o método que desejarem para resolução.
import math
import numpy as np
import random as rd
import datetime

## Questão 0
### Dr. Keynes

![image.png](attachment:image.png)

No início do século XX, o economista John Maynard Keynes revolucionou o pensamento econômico ao destacar a importância do Produto Interno Bruto (PIB) como uma medida essencial para entender a saúde de uma economia. O PIB é a soma de todos os bens e serviços finais produzidos em uma economia durante um determinado período. Para calculá-lo, basta multiplicar o valor de cada item pelo número de unidades vendidas.

Sua missão é ajudar o governo das Ilhas Cayman a calcular o PIB do país neste ano, baseado nos dados fornecidos de três setores da economia: turismo, exportação de frutas tropicais, venda de acessórios, entrada de dinheiro estrangeiro e até a venda de valiosas pinturas.

Crie duas matrizes usando o NumPy:

A primeira matriz representa o valor unitário dos itens de cada setor.

A segunda matriz representa a quantidade vendida de cada item.


Sua missão é calcular o PIB das Ilhas Cayman com base com estes dados fictícios. Multiplique as duas matrizes para descobrir o PIB das Ilhas Cayman e exiba o resultado total e printar a seguinte mensagem:
"Com base nos cálculos, o Produto Interno Bruto (PIB) das Ilhas Cayman alcança X bilhões de dólares! Graças ao turismo, à arte, às frutas tropicais e à entrada de dinheiro estrangeiro."

![image.png](attachment:image.png)

In [50]:
# Faça a multiplicação de matrizes e o print aqui
valor_unitario = np.array([1.2, 0.7, 0.3, 1.8, 2.0])

unidades_vendidas = np.array ([100, 500, 200, 300, 5])

valor_pib = np.dot(valor_unitario, unidades_vendidas)

print(f"Com base nos cálculos, o Produto Interno Bruto (PIB) das Ilhas Cayman alcança {valor_pib:.2f} bilhões de dólares!\nGraças ao turismo, à arte, às frutas tropicais e à entrada de dinheiro estrangeiro.")

Com base nos cálculos, o Produto Interno Bruto (PIB) das Ilhas Cayman alcança 1080.00 bilhões de dólares!
Graças ao turismo, à arte, às frutas tropicais e à entrada de dinheiro estrangeiro.


## Questão 1

a) Filtrando notas abaixo de 7 Um professor quer saber quais alunos tiraram notas abaixo de 7 em uma turma de 100 alunos. Dado um array com as notas de cada aluno, filtre e exiba apenas as notas menores que 7, para que o professor possa ver quais alunos precisam de ajuda.
Escreva um código para criar o array de notas e realizar o filtro das notas abaixo de 7.

In [51]:
notas = np.random.uniform(0, 10, size = 100)
notas

array([8.68478906e+00, 8.41853455e+00, 1.42991544e-01, 5.10642063e+00,
       1.90058313e+00, 1.53401720e-01, 7.67418196e+00, 6.78227951e+00,
       8.65182424e+00, 2.98818101e+00, 3.64044707e+00, 3.45326659e+00,
       1.57659887e+00, 4.47603581e+00, 4.06776725e+00, 3.04415517e+00,
       6.92699228e+00, 2.42769029e+00, 2.42495046e+00, 8.46545941e+00,
       5.58200914e+00, 5.77472527e+00, 4.46163987e+00, 7.34846235e+00,
       3.26828929e+00, 7.68717704e+00, 9.89747400e+00, 6.26447358e+00,
       6.86526338e+00, 9.67803222e+00, 1.17940533e+00, 7.93685434e+00,
       1.06181333e+00, 2.33099577e+00, 9.69689210e+00, 3.63176309e+00,
       4.91861865e-01, 1.46512911e+00, 5.78991074e+00, 7.62278325e+00,
       6.83947819e+00, 7.48579630e+00, 5.84607851e+00, 6.18361158e+00,
       2.68650962e+00, 9.65745170e+00, 7.31222890e-01, 1.47670234e+00,
       5.28024959e+00, 4.95268384e+00, 5.92755132e-01, 3.43319657e+00,
       1.78776543e-01, 5.26950045e-01, 8.41949237e+00, 4.21382299e+00,
      

In [52]:
#Escrava aqui o seu código

#Notas menores que7.00
notas[notas < 7.00]

array([1.42991544e-01, 5.10642063e+00, 1.90058313e+00, 1.53401720e-01,
       6.78227951e+00, 2.98818101e+00, 3.64044707e+00, 3.45326659e+00,
       1.57659887e+00, 4.47603581e+00, 4.06776725e+00, 3.04415517e+00,
       6.92699228e+00, 2.42769029e+00, 2.42495046e+00, 5.58200914e+00,
       5.77472527e+00, 4.46163987e+00, 3.26828929e+00, 6.26447358e+00,
       6.86526338e+00, 1.17940533e+00, 1.06181333e+00, 2.33099577e+00,
       3.63176309e+00, 4.91861865e-01, 1.46512911e+00, 5.78991074e+00,
       6.83947819e+00, 5.84607851e+00, 6.18361158e+00, 2.68650962e+00,
       7.31222890e-01, 1.47670234e+00, 5.28024959e+00, 4.95268384e+00,
       5.92755132e-01, 3.43319657e+00, 1.78776543e-01, 5.26950045e-01,
       4.21382299e+00, 4.02905925e-01, 3.82196769e+00, 1.73224478e+00,
       1.80032940e+00, 6.09425863e+00, 3.61783653e+00, 2.57403117e-01,
       6.61002990e+00, 5.61734192e+00, 2.41151055e-01, 6.69613513e+00,
       4.40344081e+00, 1.47710957e+00, 5.92715313e+00, 2.03909711e-01,
      

b) Enviando uma lista de itens para a loja

Você foi ao mercado e anotou uma lista de itens, mas percebeu que alguns deles estavam repetidos. Agora você quer enviar para a loja apenas os itens únicos. Dado um array com sua lista de compras (com repetições), crie um código que mostre a lista final sem itens duplicados.

In [53]:
lista_itens = np.array(['macarrão', 'picanha', 'feijão', 'banana', 'morango', 'picanha', 'cerveja', 'macarrão', 'cerveja', 'banana'])
lista_itens

array(['macarrão', 'picanha', 'feijão', 'banana', 'morango', 'picanha',
       'cerveja', 'macarrão', 'cerveja', 'banana'], dtype='<U8')

In [55]:
#Lista final sem itens duplicados
lista_unica = np.unique(lista_itens)
print(lista_unica)


['banana' 'cerveja' 'feijão' 'macarrão' 'morango' 'picanha']


c) Você é um explorador de planetas e precisa registrar a temperatura em 9 pontos de uma lua que você está investigando. Esses pontos estão organizados em uma grade 3x3. Crie uma matriz 3x3 para representar essas temperaturas, preenchida com números inteiros entre 100°C e 150°C, e exiba a matriz. Por fim, localize a temperatura registrada na segunda linha e terceira coluna.

In [56]:
lista_temperatura = ['100°c', '120°c', '150°c', '138°c', '112°c', '129°c', '144°c', '110°c', '105°c']


In [57]:
#Criação da matriz 3x3
matriz = np.array(lista_temperatura).reshape(3, 3)
matriz

array([['100°c', '120°c', '150°c'],
       ['138°c', '112°c', '129°c'],
       ['144°c', '110°c', '105°c']], dtype='<U5')

In [9]:
#Localização da temperatura registrada na segunda linha e terceira coluna.
temperatura = matriz[1, 2]
print(temperatura)

129°c


## Questão 2

Você é um famoso consultor financeiro internacional, constantemente viajando entre diferentes países e lidando com fusos horários variados. Como você é muito ocupado, precisa de um sistema que te ajude a organizar compromissos importantes automaticamente no horário local de cada país.

Sua missão é criar um código que, ao receber a data e hora de um compromisso em um fuso horário (GMT), seja capaz de converter essa data e hora para o fuso horário local de outros três países: Brasil (GMT-3), Japão (GMT+9) e Estados Unidos (Nova York, GMT-4).

Receba a data e hora de um compromisso (em GMT) e converta para os fusos horários locais do Brasil, Japão e Nova York.
Exiba uma mensagem para o usuário indicando os horários em cada país, facilitando a organização da agenda.

Saída Esperada:

"Seu compromisso será às 12:00 no Brasil, às 00:00 no Japão (do dia seguinte), e às 11:00 em Nova York."

In [58]:
compromisso_gmt = '2024-10-10 15:00:00'

In [61]:
# Fiz uma pesquisa na documentação do Python como vocês orientaram, e aprendi que para utilizar a biblioteca datetime, 
# especifamente com fusos horários, é necessário instalar a biblioteca pytz. Até brinquei com um códido de exemplo 
# bem simples e o pytz realmente é uma mão na roda quando se trata em conversão de datas e horários que exigem fuso horário.
# De acordo com meus estudos na documentação do Python e com base em nossos estudos anteriores, especificamente na aula 
# de Estrutura de dados, consegui escrever esse código:

# Importação da biblioteca datetime e da biblioteca pytz devidamente instalada e importada
from datetime import datetime
import pytz

# Criar objeto datetime a partir da string e definir o fuso horário GMT
data_hora_gmt = pytz.timezone('GMT').localize(datetime.strptime(compromisso_gmt, "%Y-%m-%d %H:%M:%S"))

# Criar um dicionário contendo os fusos horários locais
fusos_horarios = {
    "Brasil": 'America/Sao_Paulo',
    "Japão": 'Asia/Tokyo',
    "Nova York": 'America/New_York'
}

# Converter e formatar datas e horas
horarios = {local: data_hora_gmt.astimezone(pytz.timezone(fuso)).strftime('%H:%M') 
            for local, fuso in fusos_horarios.items()}

# Verificar se a data no Japão é do dia seguinte
dia_japao = "(do dia seguinte), " if data_hora_gmt.date() < data_hora_gmt.astimezone(pytz.timezone(fusos_horarios["Japão"])).date() else ""

# Exibir a mensagem
print(f"Seu compromisso será às {horarios['Brasil']} no Brasil, às {horarios['Japão']} no Japão {dia_japao}e às {horarios['Nova York']} em Nova York.")


Seu compromisso será às 12:00 no Brasil, às 00:00 no Japão (do dia seguinte), e às 11:00 em Nova York.


## Questão 3
Uma loja de eletrônicos está fazendo uma análise dos preços de seus produtos e quer saber quais itens estão acima do preço médio. Dado um array com os preços de 17 produtos, calcule o preço médio e o desvio padrão e exiba apenas os produtos que custam mais do que a média.

![image.png](attachment:image.png)

Escreva um código para calcular o preço médio e filtrar os produtos acima desse valor.

In [62]:
np.random.seed(10)

preço_produtos = np.random.uniform(0, 30, 17)

print(preço_produtos)

[23.1396193   0.62255848 19.00944705 22.46411648 14.95521037  6.74389937
  5.94188594 22.81592137  5.0733251   2.65019443 20.56079455 28.60180039
  0.11844799 15.3657679  24.37862885 18.375782   21.65265952]


In [63]:
# Escreva aqui o seu código

# Preço Médio
preco_medio = np.mean(preço_produtos)
desvio_padrao = np.std(preço_produtos)

acima_media = preço_produtos[preço_produtos > preco_medio]

print(f"O preço médio dos protutos é de R$ {preco_medio:.2f} com um desvio padrão de R$ {desvio_padrao:.2f}.\n") 

print(f"Os produtos com preço acima da média são: \n {acima_media}")

O preço médio dos protutos é de R$ 14.85 com um desvio padrão de R$ 9.04.

Os produtos com preço acima da média são: 
 [23.1396193  19.00944705 22.46411648 14.95521037 22.81592137 20.56079455
 28.60180039 15.3657679  24.37862885 18.375782   21.65265952]


#
Agora, utilize dos métodos .mean() e .std() para calcular a média e o desvio padrão do array anterior

In [64]:
print(f"O preço médio dos produtos acima da média é de R$ {acima_media.mean():.2f}, com um desvio padrão de R$ {acima_media.std():.2f}.")


O preço médio dos produtos acima da média é de R$ 21.03, com um desvio padrão de R$ 3.80.


## Desafio (Opcional)

Uma grande cidade está implementando um novo sistema de transporte público e precisa que você analise os dados de tráfego para otimizar a distribuição de veículos em diferentes rotas. Eles te forneceram uma matriz tridimensional que representa a quantidade de passageiros transportados em 5 linhas de ônibus, durante 7 dias da semana, em 4 diferentes horários de pico (manhã, meio-dia, tarde e noite).

Cada dimensão da matriz tem o seguinte significado:

Eixo 0: Representa as 5 linhas de ônibus.
Eixo 1: Representa os 7 dias da semana.
Eixo 2: Representa os 4 horários de pico.

Sua missão é ajudar a cidade a otimizar o sistema, resolvendo os seguintes desafios:


Média de passageiros por linha: Calcule a média de passageiros transportados em cada uma das 5 linhas de ônibus ao longo da semana.

Dia mais movimentado: Encontre qual dia da semana (entre os 7 dias) teve o maior número total de passageiros transportados em todas as linhas e horários de pico.

Horário de pico mais movimentado: Identifique qual dos 4 horários de pico (manhã, meio-dia, tarde ou noite) transporta o maior número médio de passageiros.

Redistribuição de veículos: A cidade está considerando mover veículos de linhas menos utilizadas para as mais movimentadas. Encontre as duas linhas de ônibus que têm a maior diferença no número total de passageiros ao longo da semana e proponha uma redistribuição onde 10% dos veículos da linha mais tranquila serão movidos para a linha mais movimentada.

Pico de operação: Encontre as combinações de linha, dia e horário onde o número de passageiros excede 90% do valor máximo observado em toda a matriz. Estes representam momentos de pico extremo.


Utilize operações de agregação do NumPy (como mean, sum, etc.) para resolver cada um dos desafios.
Para o último desafio, utilize a técnica de indexação booleana para encontrar as posições que atendem à condição de pico de operação.

In [65]:
np.random.seed(5)
passageiros = np.random.randint(50, 300, size=(5, 7, 4))
passageiros

array([[[149, 256, 289, 239],
        [280, 168, 194, 123],
        [ 58, 278, 281, 240],
        [205, 162, 208, 258],
        [ 57, 254, 193, 163],
        [231, 281, 130,  77],
        [ 94, 255, 253, 115]],

       [[225,  80, 262, 136],
        [175, 196, 171, 187],
        [156,  91, 283, 240],
        [179, 260, 153, 194],
        [256,  55, 108,  50],
        [258, 182, 160, 214],
        [155, 229,  77,  81]],

       [[ 52, 118,  88, 155],
        [261, 197,  68, 163],
        [295, 185, 150, 158],
        [159, 208, 240,  61],
        [285, 117, 174, 243],
        [233, 181, 141, 128],
        [205, 207,  83, 267]],

       [[135, 185,  66, 144],
        [ 64, 268,  81,  59],
        [ 88,  97, 194, 183],
        [212, 223, 237, 202],
        [191, 168, 285, 282],
        [ 81,  82, 126, 222],
        [183, 192, 225, 144]],

       [[132, 178, 281, 185],
        [264,  66, 114,  58],
        [268,  94, 176, 215],
        [144, 253, 183, 283],
        [200, 230, 119, 260],
  

In [66]:
#Média de passageiros por linha
media_por_linha = np.mean(passageiros, axis=(1, 2))
print(f"A média de passageiros por linha é: ")
*media_por_linha,

A média de passageiros por linha é: 


(np.float64(196.10714285714286),
 np.float64(171.89285714285714),
 np.float64(172.21428571428572),
 np.float64(164.96428571428572),
 np.float64(192.82142857142858))

In [67]:
#Dia mais movimentado
passageiros_por_dia = np.sum(passageiros, axis=(0, 2))

dia_mais_movimentado = np.argmax(passageiros_por_dia)

dias_da_semana = {
    0: "Segunda",
    1: "Terça",
    2: "Quarta",
    3: "Quinta",
    4: "Sexta",
    5: "Sábado",
    6: "Domingo"
}

print("Dia_mais_movimentado: ", dias_da_semana[dia_mais_movimentado])

Dia_mais_movimentado:  Quinta


In [68]:
#Horário mais movimentado
media_por_horario = np.mean(passageiros, axis=(0, 1))

horario_mais_movimentado = np.argmax(media_por_horario)

horarios = {
    0: "Manhã",
    1: "Meio-dia",
    2: "Tarde",
    3: "Noite"
}

print("Horário mais movimentado: ", horarios[horario_mais_movimentado])

Horário mais movimentado:  Meio-dia


In [69]:
#Redistribuição de  veículos
total_por_linha = np.sum(passageiros, axis=(1, 2))
linha_mais_movimentada = np.argmax(total_por_linha)
linha_menos_movimentada = np.argmin(total_por_linha)

print("Linha mais movimentada: ", linha_mais_movimentada + 1)
print("Linha menos movimentada: ", linha_menos_movimentada + 1)

print(f"Mover {total_por_linha[linha_mais_movimentada] * 0.1:.0f} passageiros da linha mais movimentada para a menos movimentada")

print(f"Valor final de cada linha:\n\tMenos movimentada: {total_por_linha[linha_menos_movimentada] + total_por_linha[linha_mais_movimentada] * 0.1:.0f}\n\tMais movimentada: {total_por_linha[linha_mais_movimentada] * 0.9:.0f}")

Linha mais movimentada:  1
Linha menos movimentada:  4
Mover 549 passageiros da linha mais movimentada para a menos movimentada
Valor final de cada linha:
	Menos movimentada: 5168
	Mais movimentada: 4942


In [70]:
#Pico de operação
max_passageiros = np.max(passageiros)
limite_pico = max_passageiros * 0.9

print(f"O limite de passageiros para o horário de pico é de {limite_pico:.0f} passageiros")

print("\n")

picos_de_operacao = np.argwhere(passageiros > limite_pico)

print("Momentos de pico extremo (linha, dia, horário):\n", picos_de_operacao)

O limite de passageiros para o horário de pico é de 266 passageiros


Momentos de pico extremo (linha, dia, horário):
 [[0 0 2]
 [0 1 0]
 [0 2 1]
 [0 2 2]
 [0 5 1]
 [1 2 2]
 [2 2 0]
 [2 4 0]
 [2 6 3]
 [3 1 1]
 [3 4 2]
 [3 4 3]
 [4 0 2]
 [4 2 0]
 [4 3 3]
 [4 5 3]
 [4 6 1]
 [4 6 2]]
